# Generated by Django 4.1.2 on 2022-10-09 18:45
from typing import Any, List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=2000)),
                ("create_time", models.DateTimeField(verbose_name="create time")),
                ("last_edit_time", models.DateTimeField(verbose_name="last edit time")),
            ],
        ),
    ]
